### ISSUE TITLE
flow validate succeeds on invalid connection

### ISSUE THREAD

**Issue by feluelle** [astronomer/astro-sdk#1096]
When validating a connection such as:
```yaml
connections:
  - conn_id: sqlite_conn_invalid
    conn_type: sqlite
    host: data/imdb2.db
    login:
    password:
    schema:
```

..the validate command succeeds even-though the db seems to not exists. This is because under the hood airflows `test_connection` command creates the sqlite database if it does not exist.
