### ISSUE TITLE
SQL CLI Load operator YAML interface

### ISSUE THREAD

**Issue by tatiana** [astronomer/astro-sdk#1165]
**Please describe the feature you'd like to see**
Declare the interface of the YAML for load file operator in SQL CLI

**Describe the solution you'd like**
Each yaml within the workflows directory would represent a single Load File task.

e.g. The directory called `example_load_file` would mean a DAG is created with its name being the same as directory name. 
Inside the directory, we can have a file called `homes_main.yaml` which would mean `homes_main` is the name of the table into which data is to be loaded.

The yaml can appear like the below and is open for discussion:
```
task/operator:
  name: load_file
  input_file:
    path: "s3://tmp9/homes_main.csv"
    conn_id: "aws_conn"
  output_table:
    conn_id: "aws_conn"
    metadata:
      schema: "astro"
      database: "dev"
```

TODO: Discuss if there would be dependencies between the YAMLs and how to define those.

**Comment by tatiana** [comment]
We should be using the `aql.load_file`, we need to discuss and define how on the SQL CLI

**Comment by tatiana** [comment]
Create a `YML` interface, @dimberman to share a proposal of interface

**Comment by tatiana** [comment]
Idea: to have 1:1 mapping (1 YAML -> 1 `aql.load_file`

**Comment by pankajkoti** [comment]
The decided interface looks like this:
```

load_file:
 input_file:
   path: "s3://tmp9/homes_main.csv"
   conn_id: "aws_conn"
 output_table:
   conn_id: "aws_conn"
   metadata:
     schema: "astro"
     database: "dev"
```
