### ISSUE TITLE
Verify docs has correct syntax for specifying connection

### ISSUE THREAD

**Issue by pankajkoti** [astronomer/astro-sdk#1255]
In the [docs](https://docs.astronomer.io/astro/cli/sql-cli#configure-environments-and-connections), We specify the connection configuration for Snowflake as 
```
snowflake_default:
  login: mylogin
  password: mypassword
  schema: myschema
  account: myaccount
  database: MYDATABASE
  region: us-east-1
  warehouse: MYWAREHOUSE
  role: ADMIN
```

But the format may need to be like this in the docs for configuration.yaml:
```
connections:
  - conn_id: snowflake_conn
    conn_type: snowflake
    host: HOST_DNS
    port: 443
    login: Username
    password: Password
    schema: "SchemaName"
    extra:
      account: "AcountId"
      region: "us-east-1"
      role: "Role"
      warehouse: Warehouse
      database: Database
```

![Screenshot 2022-11-16 at 12.39.36 AM.png](https://images.zenhubusercontent.com/624476b10ffe431c7bb98647/4420631a-2633-4695-a348-12211836bedd)
