### ISSUE TITLE
Example Google Cloud connection for SQL-CLI that uses private key file

### ISSUE THREAD

**Issue by mikeshwe** [astronomer/astro-sdk#1327]
so that we can use SQL-CLI with GCS and BQ

**Comment by feluelle** [comment]
The example from the sql-cli works as expected - also in astro-cli.

For sql-cli, define the following connection in a connections file such as `config/default/configuration.yml`:
```yaml
- conn_id: bigquery_conn
  conn_type: gcpbigquery
  extra: '{"extra__google_cloud_platform__project": "$GOOGLE_CLOUD_PROJECT", "extra__google_cloud_platform__key_path": "$GOOGLE_CLOUD_KEY_PATH"}'
```
and the environment variables used, in the `.env` file of the sql-cli or astro-cli-flow project:
```env
GOOGLE_CLOUD_PROJECT=<project-name>
GOOGLE_CLOUD_KEY_PATH=<key-path>
```
> **_Note for the astro-cli-flow project_**
The key-path needs to be within the project directory i.e. `<project-dir>/<key-file>`, because this is, by default, the only directory which is available to the container running sql-cli - **and** the path needs to be absolute as this is what also exists in the container running sql-cli.
