### ISSUE TITLE
Add Google Drive support & example

### ISSUE THREAD

**Issue by tatiana** [astronomer/astro-sdk#1332]
Give an example of loading from google drive.

**Comment by kaxil** [comment]
Where are we on this @tatiana ?

**Comment by tatiana** [comment]
Define the following connection in a connections file such as `config/default/configuration.yml`:

```
- conn_id: gdrive_conn
  conn_type: google_cloud_platform
  extra: '{"extra__google_cloud_platform__scope": "https://www.googleapis.com/auth/drive.readonly"}'
```

Add sensitive information to a `.env` file in the Astro CLI / SQL workflow project:

```
GOOGLE_CLOUD_PROJECT=<project-name>
GOOGLE_CLOUD_KEY_PATH=<key-path>
```

This will allow users to do load operations using the SQL CLI by using:
```
load_file:
  input_file:
    conn_id: "gdrive_conn"
    path: "gdrive://test-google-drive-support/sample.csv"
  output_table:
    conn_id: "snowflake_conn"
```
