### ISSUE TITLE
All connections tested even though one's been specified

### ISSUE THREAD

**Issue by magdagultekin** [astronomer/astro-sdk#1370]
**Describe the bug**
I ran `astro flow validate --connection=<connection_id>` and all connections were tested even though I passed one conn id specifically. 

**Version**
* Astro Runtime: 7.0.0
* Astro CLI: 1.8.3

**To Reproduce**
1. Update file `config/default/configuration.yml` as shown below:
```
connections:
  - conn_id: sqlite_conn
    conn_type: sqlite
    host: /Users/magdagultekin/magda-dev/data/imdb.db
    login: null
    password: null
    schema: null
  - conn_id: sqlite_default
    conn_type: sqlite
    host: /tmp/sqlite.db
    login: null
    password: null
    schema: null
```
4. Run `astro flow validate --connection=sqlite_default`
5. See message:
```
Validating connection(s) for environment 'default'
Validating connection sqlite_conn               PASSED
Validating connection sqlite_default            FAILED
```

**Expected behavior**
Only `sqlite_default` should be tested.

**Screenshots**
![image](https://user-images.githubusercontent.com/97064715/205905971-7c71dc2d-36c8-44ac-9857-9e98180c5ef4.png)
