### ISSUE TITLE
Connection not found even though exists in configuration.yml

### ISSUE THREAD

**Issue by magdagultekin** [astronomer/astro-sdk#1371]
**Describe the bug**
I added `sqlite_default` connection to `config/default/configuration.yml` file and ran `astro flow validate --connection=sqlite_default` and the connection was not found even though it exists in the file.

**Version**
* Astro Runtime: 7.0.0
* Astro CLI: 1.8.3

**To Reproduce**
1. Update file `config/default/configuration.yml` as shown below:
```
connections:
  - conn_id: sqlite_conn
    conn_type: sqlite
    host: /Users/magdagultekin/magda-dev/data/imdb.db
    login: null
    password: null
    schema: null
  - conn_id: sqlite_default
    conn_type: sqlite
    host: /tmp/sqlite.db
    login: null
    password: null
    schema: null
```
4. Run `astro flow validate --connection=sqlite_default`
5. See message:
```
Validating connection(s) for environment 'default'
Validating connection sqlite_conn               PASSED
Validating connection sqlite_default            FAILED
Error: Config file does not contain given connection sqlite_default
```

**Expected behavior**
Project should pick up the `sqlite_default` connection.

**Screenshots**
![image](https://user-images.githubusercontent.com/97064715/205906618-5f76b8c7-9b52-473a-bd57-bf333c77bb5f.png)
