### ISSUE TITLE
Allow SQL CLI users to define scheduling and other DAG metadata using YML

### ISSUE THREAD

**Issue by tatiana** [astronomer/astro-sdk#1528]
**Context**

The `flow generate` command allows users to generate an Airflow Python DAG from a SQL CLI workflow.

As part of the SQK CLI deployment journey (#1520), we want to allow users to use YML files to describe DAG properties (including scheduling).

Users should be able to define a file `config.yaml` inside `<proj-dir>/workflows/<workflow>/`, using the syntax:

```yaml
workflow:
     description: 
     schedule: “@daily” # examples in the sample files! - some based on cron
     start_date: ”2015-12-1”
     end_date:
     is_paused_upon_creation: true
```
and

```yaml
workflow:
     description: 
     schedule: "s3://dataset-bucket/example.csv"
     start_date:
     end_date:
     is_paused_upon_creation: false
```

**Goal**

The properties defined in the YML file should be made available in the generated DAG when users run `flow generate`.
