### ISSUE TITLE
Set the CI to run and publish benchmark reports once a week

### ISSUE THREAD

**Issue by tatiana** [astronomer/astro-sdk#443]
**Dependencies**
* Depends on: #432 
* Depends on: #434
* Depends on: #442 
* Depends on one of:
  * #438
  * #431
  * #437

**Acceptance criteria**
* [ ] The CI should run the benchmark & analysis scripts on a weekly basis for all scenarios defined
* [ ] If any of the benchmark scenarios had a performance degradation of 10% (took 10% of the time more than the previous execution of that same scenario) - we should notify in slack
* [ ] The markdown created by the analysis script should be committed to the repo
* [ ] Script to compare benchmarking results with previous run

**Comment by tatiana** [comment]
Just giving additional information, this feature was requested by @vikramkoka during a meeting with him - and the goal is to make sure our benchmark results are always up-to-date with the current performance of the Astro Python SDK.

**Comment by pankajastro** [comment]
I have started working on this

**Comment by pankajkoti** [comment]
@pankajastro explored Github Actions and will try out Github action along the lines of this ticket today.

**Comment by pankajastro** [comment]
There is a scheduled event in GitHub workflow but looks like it runs on the default branch only i.e main our case so we might have to merge PR in order to full end-to-end test. I have tested the scheduling part on my private repo it seems to be working. Currently, trying to test the benchmark make command in separate job once this succeeds then we should be able to combine both together

**Comment by pankajastro** [comment]
trying to run below job
```
Run-Benchmark:
    runs-on: ubuntu-18.04
    env:
      GOOGLE_APPLICATION_CREDENTIALS: /tmp/google_credentials.json
      GOOGLE_APPLICATION_CREDENTIALS_JSON: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_JSON }}
    steps:
      - uses: actions/checkout@v2
      - run: python -c 'import os; print(os.getenv("GOOGLE_APPLICATION_CREDENTIALS_JSON", "").strip())' > ${{ env.GOOGLE_APPLICATION_CREDENTIALS }}
      - run: cd tests/benchmark && make
```

Error: Error when reading or editing Project Service ***-***-****/container.googleapis.com: Failed to list enabled services for project astronomer-dag-authoring: googleapi: Error 403: Permission denied to list services for consumer container
