### ISSUE TITLE
[POC] Openlineage support - Add Extractor for `LoadFileOperator`

### ISSUE THREAD

**Issue by kaxil** [astronomer/astro-sdk#898]
**Please describe the feature you'd like to see**
This is our first step toward adding openlineage support in the SDK. We should be able to extract open lineage info from the `LoadFileOperator`.

**Describe the solution you'd like**
- Add a method `get_openlineage_facets` on the Operator (based on [this doc](https://docs.google.com/document/d/1vPsvHejQ24xTbzpz_LYSf0_ixk9oUuBiEUHVEaF9J2U/edit?usp=sharing))
- Build a "PythonSDKExtractor" that looks for `get_openlineage_facets` on any operator, so that it works for all the operators in the SDK

Depends on:

- [x] #1005 @sunank200 
- [ ] #1025 Implement PythonSDK extractor and `get_openlineage_facets(ti)` on loadFile method returning the structure defined below.
Facets are the json facets defined in the [OpenLineage specification](https://github.com/OpenLineage/OpenLineage/blob/main/spec/OpenLineage.md)
```
TaskInstanceLineage:
	runFacets: dict{}
	jobFacets: dict{}
        inputs: [InputDataset]
        outputs: [OutputDataset]
 
InputDataset:
	namespace: string
	name: string
	facets: dict{}
	inputFacets: dict{}

OutputDataset:
	namespace: string
	name: string
	facets: dict{}
	outputFacets: dict{}
```
- [x] Add relevant facets along with an example DAG
- [x] Add tests
- [ ] Add Marquez as part of CI

**Additional context**
- We do not want to build an extractor for each operator in the SDK so we will just build one extractor that calls ``get_openlineage_facets`` on any SDK operator based on [this doc](https://docs.google.com/document/d/1vPsvHejQ24xTbzpz_LYSf0_ixk9oUuBiEUHVEaF9J2U/edit?usp=sharing)
- This extractor can live in the SDK for now but `openlineage-airflow` will add this extractor after we do this POC
- Sync up with openlineage team once the POC is completed successfully
- **Failure of the extractor** should not affect the operator itself so add necessary try..catch wherever applicable and test it thoroughly
- We should make sure that there are no dependency conflicts for openlineage-airflow package in the Runtime image if someone installs Python SDK

**Acceptance Criteria**

- [ ] Post the screenshot of how it looks in the Openlineage/Marquez UI
- [ ] All checks and tests in the CI should pass
- [ ] Unit tests (90% code coverage or more, [once available](https://github.com/astronomer/astro-sdk/issues/191))
- [ ] Integration tests (if the feature relates to a new database or external service)
- [ ] Docstrings in [reStructuredText](https://peps.python.org/pep-0287/) for each of  methods, classes, functions and module-level attributes (including Example DAG on how it should be used)
- [ ] Exception handling in case of errors
- [ ] Logging (are we exposing useful information to the user? e.g. source and destination)
- [ ] Improve the documentation (README, Sphinx, and any other relevant)
