### ISSUE TITLE
Create or replace existing local Airflow connections using YAML

### ISSUE THREAD

**Issue by tatiana** [astronomer/astro-sdk#930]
**Please describe the feature you'd like to see**

Given a previously generated project structure:
```
sql-test/
    config/
        local/
            configuration.yml
        dev/
            configuration.yml
    workflows/
        workflow_example1/
            example_1a.sql
            example_1b.sql
    .dags/
```
In which a configuration.yml contains:
```
connections:
  - conn_id: postgres_conn
    conn_type: postgres
    host: localhost
    schema:
    login: postgres
    password: postgres
    port: 5433
    extra:
```

Implement a Python function which receives the environment (e.g. local) and creates or replaces all the connections in Airflow.

**Acceptance Criteria**

- [ ] All checks and tests in the CI should pass
- [ ] Unit tests (90% code coverage or more, [once available](https://github.com/astronomer/astro-sdk/issues/191))
- [ ] Integration tests (if the feature relates to a new database or external service)
- [ ] Example DAG
- [ ] Docstrings in [reStructuredText](https://peps.python.org/pep-0287/) for each of  methods, classes, functions and module-level attributes (including Example DAG on how it should be used)
- [ ] Exception handling in case of errors
- [ ] Logging (are we exposing useful information to the user? e.g. source and destination)
- [ ] Improve the documentation (README, Sphinx, and any other relevant)
- [ ] How to use Guide for the feature ([example](https://airflow.apache.org/docs/apache-airflow-providers-postgres/stable/operators/postgres_operator_howto_guide.html))
